### ISSUE TITLE
undefined method 'track_ga_event' for [controller]

### ISSUE THREAD

**Issue by davev** [kangguru/rack-google-analytics#16]
using Rails 3.2.13.  

in config/application.rb:
config.middleware.use Rack::GoogleAnalytics, {
        :tracker => ENV["GOOGLE_ANALYTICS_URCHIN_ID"],
        :async => true
      }

in any controller:
track_ga_event(current_user.email, "Page View", request.try(:path_info)) if current_user

i get a NoMethod Error:
undefined method 'track_ga_event' for ...

it's not recognizing the two instance methods.  am i missing something obvious?  tia.

**Comment by jontonsoup** [comment]
did you ever solve this?

**Comment by davev** [comment]
no, ended up just including the custom event/user var calls directly as javascript.

**Comment by ddefrenne** [comment]
The file which would include track_ga_event into the controller was never being called. It's fixed in https://github.com/leehambley/rack-google-analytics/pull/17.

**Comment by kavyavj** [comment]
I am using rack-google_analytics (1.0.2) and still getting NoMethodError:undefined method `track_ga_event' 
in  Rails 3.2.13
